print ("Contesta las siguientes preguntas:")
Nombre = input ("¿Cómo te llamas?")
print (f"Un gusto {Nombre} , Buen nombre.")
Edad = int (input (f"¿Cuántos años tienes?"))
print (f"Ya veo. {Edad} , nada mal.")
